name: sia-release

on:
  workflow_dispatch:
    inputs:
      proyecto:
        type: choice
        description: 'Proyecto de SAM a desplegar'
        required: true
        options:
        - sia-utileria-notificaciones-teams
        - sia-afore-md
        - sia-afore-mo
        - trunk-based
      version:
        type: string
        description: 'Número de versión de la liberación'
        required: true
        
jobs:
  release:
    runs-on: ubuntu-latest
    environment: develop
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: Send greeting
      run: |
        echo "Hello $HOME"
        echo $PWD
        pwd
    - name: Configurar Git
      run: |
        git config --global user.name 'SIAGithub'
        git config --global user.email 'sia@noreply.github.com'
        git branch --show-current
    - name: Separar cambios
      run: |
        mkdir ./splitsh
        echo "wget"
        wget https://github.com/splitsh/lite/releases/download/v1.0.1/lite_linux_amd64.tar.gz
        echo "ls"
        ls -la
        echo "tar"
        tar --verbose -zxpf lite_linux_amd64.tar.gz --directory ./splitsh
        ls -la ./splitsh
        ./splitsh/splitsh-lite --prefix=afore/workflows/trunk-based --target=refs/heads/releases/${{github.event.inputs.proyecto}}/${{github.event.inputs.version}} --progress
    - name: Crear rama release
      run: |
        git checkout releases/${{github.event.inputs.proyecto}}/${{github.event.inputs.version}}
        git tag ${{github.event.inputs.proyecto}}/${{github.event.inputs.version}}
        git push --tags -u origin releases/${{github.event.inputs.proyecto}}/${{github.event.inputs.version}}  
    - uses: aws-actions/setup-sam@v0
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: us-east-1
    - name: Publicar aplicación
      run: |
        sam package --template-file template.yaml \
          --output-template-file packaged.yaml \
          --s3-bucket pfg-sia-sam-trunk-based \
          --s3-prefix "${{github.event.inputs.proyecto}}/${{github.event.inputs.version}}"
        sam publish --template packaged.yaml --region us-east-1
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{github.event.inputs.proyecto}}/${{github.event.inputs.version}}
        generate_release_notes: true
