name: Tag Checkout

on:
  pull_request:
    branches: [ develop ]

  workflow_dispatch:
    inputs:
      ambiente:
        type: choice
        description: 'Ambiente al cual se despliega'
        required: true
        options:
        - develop
        - preprod
        - production
      proyecto:
        type: choice
        description: 'Pruebas con Tag Checkout'
        required: true
        options:
        - sia-utileria-notificaciones-teams
        - sia-afore-md
        - sia-afore-mo
      version:
        type: string
        description: 'Número de versión de la liberación'
        required: true
jobs:
################ PRODUCTION #######################
  deployProduction:

    runs-on: ubuntu-latest

    environment: ${{github.event.inputs.ambiente}}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/tags/${{github.event.inputs.proyecto}}/${{github.event.inputs.version}}
      - name: Listar interior
        run: |
          ls -la
          git show
          git status
          echo ${{secrets.MENSAJE}} | sed 's/./& /g'

