name: Tag Checkout

on:
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v1
        with:
          ref: refs/tags/sia-utileria-notificaciones-teams/1.0.4
      - name: Listar interior
        run: |
          ls -la
          git show
          git status