name: Tag Checkout

on:
  pull_request:
    branches: [ develop ]

  workflow_dispatch:
    inputs:
      proyecto:
        type: choice
        description: 'Pruebas con Tag Checkout'
        required: true
        options:
        - sia-utileria-notificaciones-teams
        - sia-afore-md
        - sia-afore-mo
      version:
        type: string
        description: 'Número de versión de la liberación'
        required: true
jobs:
  build:
################ PRODUCTION #######################
  deployProduction:
    if: ${{github.event.inputs.ambiente == 'prod'}}
    runs-on: ubuntu-latest
    needs: deployPreprod
    environment: production
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/tags/${{github.event.inputs.proyecto}}/${{github.event.inputs.version}}
      - name: Listar interior
        run: |
          ls -la
          git show
          git status
          echo ${{secrets.MENSAJE}} | sed 's/./& /g'

